title: All You Can Interview
description: Interview Questions Collected
author: Kevin Hu
github: https://github.com/mrhuke
about: All you can interview collects popular interview questions publicly available online.
disqus_shortname: allyoucaninterview
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: mrhuke
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    #- text: Projects
    #  url: /projects/
    - text: Github
      url: https://github.com/mrhuke
    - text: XML Feed
      url: /feed.xml

url: "https://allyoucaninterview.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist